In [1]:
import nltk

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [2]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [3]:
ps = PorterStemmer()
lm = WordNetLemmatizer()

In [4]:
my_string = '''Other collaborative online encyclopedias were attempted before Wikipedia, but none were as successful.[13] Wikipedia began as a complementary project for Nupedia, a free online English-language encyclopedia project whose articles were written by experts and reviewed under a formal process.[14] It was founded on March 9, 2000, under the ownership of Bomis, a web portal company. Its main figures were Bomis CEO Jimmy Wales and Larry Sanger, editor-in-chief for Nupedia and later Wikipedia.[15][16] Nupedia was initially licensed under its own Nupedia Open Content License, but even before Wikipedia was founded, Nupedia switched to the GNU Free Documentation License at the urging of Richard Stallman.[17] Wales is credited with defining the goal of making a publicly editable encyclopedia,[18][19] while Sanger is credited with the strategy of using a wiki to reach that goal.[20] On January 10, 2001, Sanger proposed on the Nupedia mailing list to create a wiki as a "feeder" project for Nupedia.[21]'''

In [10]:
my_string

'Other collaborative online encyclopedias were attempted before Wikipedia, but none were as successful.[13] Wikipedia began as a complementary project for Nupedia, a free online English-language encyclopedia project whose articles were written by experts and reviewed under a formal process.[14] It was founded on March 9, 2000, under the ownership of Bomis, a web portal company. Its main figures were Bomis CEO Jimmy Wales and Larry Sanger, editor-in-chief for Nupedia and later Wikipedia.[15][16] Nupedia was initially licensed under its own Nupedia Open Content License, but even before Wikipedia was founded, Nupedia switched to the GNU Free Documentation License at the urging of Richard Stallman.[17] Wales is credited with defining the goal of making a publicly editable encyclopedia,[18][19] while Sanger is credited with the strategy of using a wiki to reach that goal.[20] On January 10, 2001, Sanger proposed on the Nupedia mailing list to create a wiki as a "feeder" project for Nupedia.

In [5]:
import re
sentences = nltk.sent_tokenize(my_string)
for i in range(len(sentences)):
    sentences[i] = re.sub('[^a-zA-Z]',' ',sentences[i]).lower()
    words = nltk.word_tokenize(sentences[i])
    words = [lm.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)


# Bag of Words

In [22]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |  
 |  Parameters
 |  ------

In [24]:
sentences = sentences[0:-1]

In [25]:
sentences

['collaborative online encyclopedia attempted wikipedia none successful',
 'wikipedia began complementary project nupedia free online english language encyclopedia project whose article written expert reviewed formal process',
 'founded march ownership bomis web portal company',
 'main figure bomis ceo jimmy wale larry sanger editor chief nupedia later wikipedia',
 'nupedia initially licensed nupedia open content license even wikipedia founded nupedia switched gnu free documentation license urging richard stallman',
 'wale credited defining goal making publicly editable encyclopedia sanger credited strategy using wiki reach goal',
 'january sanger proposed nupedia mailing list create wiki feeder project nupedia']

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(sentences).toarray()

In [32]:
X

array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 0,

In [33]:
X.shape()

TypeError: 'tuple' object is not callable

## TF-IDF

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(sentences).toarray()

In [8]:
X

array([[0.        , 0.42154559, 0.        , 0.        , 0.        ,
        0.        , 0.42154559, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30485864, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.42154559, 0.        , 0.3532881 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.42154559, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.26729384,
        0.        ],
       [0.24587492, 0.        , 0.24587492, 0.        , 0.        ,
        0.        , 0.     

## Fake News Classifier

In [1]:
import pandas as pd
df =  pd.read_csv("fake_news_classifier.csv")

In [2]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL

In [4]:
df = df.dropna()

In [6]:
df.shape

(6335, 4)

In [8]:
pd.get_dummies(df,columns = ['label'])

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  label_FAKE  \
0     Daniel Greenfield, a Shillman Journalism Fello...           1   
1     Google Pinterest Digg Linkedin Reddit Stumbleu...           1   
2     U.S. Secretary of State John F. Kerry said Mon...           0   
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...           1   
4     It's primary day in New York and front-runners...           0   
...                                                 ...         ...   
6330  The State Department told the Republican Natio...           0   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...           1   
6332   Anti-Trump Protesters Are Tools of the Oligar...           1   
6333  ADDIS ABABA, Ethiopia —President Obama convene...           0   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...           0   

      label_REAL  
0              0  
1              0  
2              1  
3              0  
4              1  
...          ...  
6330           1  
6331           0  
6332           0  
6333           1  
6334           1  

[6335 rows x 5 columns]

In [22]:
fake = pd.get_dummies(df['label'])

In [24]:
y = fake['FAKE']

In [25]:
y

0       1
1       1
2       0
3       1
4       0
       ..
6330    0
6331    1
6332    1
6333    0
6334    0
Name: FAKE, Length: 6335, dtype: uint8

In [26]:
x = df.loc[:,['title','text']]

In [27]:
x

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text  
0     Daniel Greenfield, a Shillman Journalism Fello...  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  
2     U.S. Secretary of State John F. Kerry said Mon...  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  
4     It's primary day in New York and front-runners...  
...                                                 ...  
6330  The State Department told the Republican Natio...  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  
6332   Anti-Trump Protesters Are Tools of the Oligar...  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  

[6335 rows x 2 columns]

In [31]:
for i in range(0,len(df['title'])):
    df.loc[i,"new_text"] = df['title'][i] + " " + df['text'][i]

In [32]:
df.head()

Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  \
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE   
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE   
2  U.S. Secretary of State John F. Kerry said Mon...  REAL   
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE   
4  It's primary day in New York and front-runners...  REAL   

                                            new_text  
0  You Can Smell Hillary’s Fear Daniel Greenfield...  
1  Watch The Exact Moment Paul Ryan Committed Pol...  
2  Kerry to go to Paris in gesture of sympathy U....  
3  Bernie supporters on Twitter erupt in anger ag...  
4  The Battle of New York: Why This Primary Matte...

In [64]:
x = df['new_text']

In [65]:
x.head()

0    You Can Smell Hillary’s Fear Daniel Greenfield...
1    Watch The Exact Moment Paul Ryan Committed Pol...
2    Kerry to go to Paris in gesture of sympathy U....
3    Bernie supporters on Twitter erupt in anger ag...
4    The Battle of New York: Why This Primary Matte...
Name: new_text, dtype: object

In [38]:
x_title = df['title']

In [36]:
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
ps = PorterStemmer()

In [ ]:
for i in range(0,len(x)):
    x[i] = re.sub('^[a-zA-Z]',' ',x[i]).lower().split()
    x[i] = [ps.stem(word) for word in x[i] if not word in stopwords.words('english')]
    x[i] = ' '.join(x[i])

<ipython-input-66-925b5dbe9b1f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i] = re.sub('^[a-zA-Z]',' ',x[i]).lower().split()
<ipython-input-66-925b5dbe9b1f>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i] = [ps.stem(word) for word in x[i] if not word in stopwords.words('english')]
<ipython-input-66-925b5dbe9b1f>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i] = ' '.join(x[i])


In [42]:
x_title[1]

'atch exact moment paul ryan commit polit suicid trump ralli (video)'

In [55]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,ngram_range=(1,3))
X = cv.fit_transform(x_title).toarray()

In [56]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.3)

In [58]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [59]:
model.fit(X_train,Y_train)

MultinomialNB()

In [60]:
pred = model.predict(X_test)

In [50]:
pred

array([1, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [61]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred,Y_test)

In [62]:
cm

array([[797, 256],
       [121, 727]])

In [63]:
accuracy_score(pred,Y_test)

0.8016833245660179